### ISSUE TITLE
Mod isnt going

### ISSUE THREAD

**Issue by robinkaulfuss** [bbenoist/FS19_SpeedRadar#6]
Hey, everytime when i try to place a radar, there is standing that there are to much of this objects and when i press "Esc" i cant move anymore.

**Comment by bbenoist** [comment]
Hi it's not my mod. I never released my own one.

**Comment by robinkaulfuss** [comment]
Can you send me yours?

**Comment by robinkaulfuss** [comment]
> Hi it's not my mod. I never released my own one.

Can you send me yours?
